services:
  pz-dashboard:
    build: .
    volumes:
      - /home/pz/firestore_backups:/backups  # monta la cartella dei backup
      - /home/pz/.secrets:/secrets
      - /home/pz/certs:/certs
    ports:
      - "80:5000"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    name: shared_backend