services:
  pz-dashboard:
    build: .
    volumes:
      - ./data:/app/data  # monti tutta la cartella
      - /home/pz/firestore_backups:/backups  # monta la cartella dei backup
    ports:
      - "80:5000"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    name: shared_backend